"""Initial schema with users, api_keys, and usage tables

Revision ID: 98ded3f2100f
Revises: 
Create Date: 2025-11-06 14:57:21.104641

"""
from typing import Sequence, Union
import sys
import os

# Add parent directory to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(__file__))))

from alembic import op
import sqlalchemy as sa
from app.database import GUID


# revision identifiers, used by Alembic.
revision: str = '98ded3f2100f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('tier', sa.Enum('FREE', 'PRO', 'TEAM', 'ENTERPRISE', name='usertier'), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('enterprise_slug', sa.String(length=255), nullable=True),
    sa.Column('enterprise_contact', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enterprise_slug'),
    sa.UniqueConstraint('stripe_customer_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_override', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('usage_summary',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=True),
    sa.Column('total_tokens_saved', sa.BigInteger(), nullable=True),
    sa.Column('total_cost_saved_usd', sa.Float(), nullable=True),
    sa.Column('requests_by_strategy', sa.JSON(), nullable=True),
    sa.Column('tokens_by_strategy', sa.JSON(), nullable=True),
    sa.Column('avg_compression_ratio', sa.Float(), nullable=True),
    sa.Column('avg_compression_time_ms', sa.Float(), nullable=True),
    sa.Column('cache_hit_rate', sa.Float(), nullable=True),
    sa.Column('tokens_limit', sa.BigInteger(), nullable=True),
    sa.Column('overage_tokens', sa.BigInteger(), nullable=True),
    sa.Column('overage_cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_summary_user_id'), 'usage_summary', ['user_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('api_key_id', GUID(), nullable=True),
    sa.Column('original_tokens', sa.Integer(), nullable=False),
    sa.Column('compressed_tokens', sa.Integer(), nullable=False),
    sa.Column('tokens_saved', sa.Integer(), nullable=False),
    sa.Column('compression_ratio', sa.Float(), nullable=False),
    sa.Column('strategy', sa.String(length=20), nullable=False),
    sa.Column('compression_time_ms', sa.Float(), nullable=False),
    sa.Column('cached', sa.Boolean(), nullable=True),
    sa.Column('cost_saved_usd', sa.Float(), nullable=True),
    sa.Column('request_metadata', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_api_key_id'), 'usage_records', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_usage_records_day'), 'usage_records', ['day'], unique=False)
    op.create_index(op.f('ix_usage_records_month'), 'usage_records', ['month'], unique=False)
    op.create_index(op.f('ix_usage_records_timestamp'), 'usage_records', ['timestamp'], unique=False)
    op.create_index(op.f('ix_usage_records_user_id'), 'usage_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_usage_records_year'), 'usage_records', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_records_year'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_user_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_timestamp'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_month'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_day'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_api_key_id'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_usage_summary_user_id'), table_name='usage_summary')
    op.drop_table('usage_summary')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
